exhibitors:
  facets:
    - key: what_we_sell
      weight: 1.0
    - key: problems_we_solve
      weight: 0.9
    - key: who_we_help
      weight: 0.8
    - key: our_expertise
      weight: 0.7
    - key: industries_we_serve
      weight: 0.6
    - key: why_visit_us
      weight: 0.5

sessions:
  facets:
    - key: session_topic
      weight: 1.0
    - key: learning_outcomes
      weight: 0.9
    - key: target_audience
      weight: 0.8
    - key: industry_focus
      weight: 0.7
    - key: practical_applications
      weight: 0.8
    - key: speaker_expertise
      weight: 0.6

speakers:
  facets:
    - key: speaker_expertise
      weight: 1.0
    - key: speaking_topics
      weight: 0.9
    - key: audience_value
      weight: 0.8
    - key: speaker_background
      weight: 0.7
    - key: connect_with_me
      weight: 0.5
